CREATE TABLE CUSTOMER(
   customer_id BIGINT NOT NULL AUTO_INCREMENT,
   first_name VARCHAR(100) NOT NULL,
   last_name VARCHAR(40) NOT NULL,
   email VARCHAR(100) NOT NULL,
   PRIMARY KEY ( customer_id )
);