DROP TABLE IF EXISTS role;
CREATE TABLE role (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


LOCK TABLES role WRITE;
INSERT INTO role VALUES (20,'ROLE_USER');
UNLOCK TABLES;