
CREATE TABLE USER_AUTHORITY (
  user_id INTEGER UNSIGNED NOT NULL,
  authority_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, authority_id),
  CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES USERS (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT authority_id FOREIGN KEY (authority_id) REFERENCES AUTHORITIES (authority_id) ON DELETE CASCADE ON UPDATE CASCADE);
