CREATE TABLE USERS (
  user_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  enabled TINYINT NOT NULL,
  PRIMARY KEY (user_id),
  UNIQUE INDEX user_id_UNIQUE (user_id ASC) VISIBLE,
  UNIQUE INDEX username_UNIQUE (username ASC) VISIBLE);
